export const RouteNames = {
  SPLASH: 'splash',
  SCAN_NFC: 'scan_nfc',
  SCAN_QR: 'scan_qr',
  HOME_STACK: 'home_stack',
  LOGIN: 'login',
  DRAWER_NAV: 'drawer_navigator',
  SIGNUP: 'signup',
  OTP: 'otp',
  FORGOT_PASSWORD: 'forgot_password',
  INTRO: 'intro',
  BOOTTOM_TABS_ROOT: 'bottom_tabs_root',
  CHOOSE_METHOD: 'choose_method',
  NEW_PASSWORD: 'new_password',
  HOME: 'home',
  ROOT_NAV: 'root_nav',
  HOME_STACK_NAV: 'home_stack_nav',
  APP_NAVIGATOR: 'app_navigator',
  HOME_STACK_SCREEN: 'Home',
  CHANGE_PASSWORD: 'Change Password',
  SETTINGS: 'Settings',
  CONTACTS: 'Contacts',
  IMPRINT: 'Imprint',
  QR_HISTORY: 'qr-history',
  APP_HOME_STACK_NAV: 'app_home_stack_nav',
  HISTORY_STACK_NAV: 'HISTORY_STACK_NAV',
  HISTORY_STACK_SCREEN: 'HISTORY_STACK_SCREEN',
  MODULE_CONFIG: 'module_config',
  ORDER_DETAILS: 'order_details',
  PROJECT_SETTINGS: 'project_settings',
  CONNECT_INFORMATION: 'connect_information',
  MSF: 'msf',
  REMARK: 'remark',
  MODULE_HISTORY: 'module_history',
  VIEW_PDF: 'View PDF',
  KOMAX_DIRECT: 'komax_direct',
  START_QR: 'start_qr',
};
