export const defaultTheme = {
  fontSizeLargeDisplay: 25,
  fontSizeDisplay: 22,
  fontSizeSubDisplay: 20,
  fontSizeHeader: 18,
  fontSizeTitle: 16,
  fontSizeSubheading: 14,
  fontSizeBodyLarge: 13,
  fontSizeBody: 12,
  fontSizeCaption: 10,
  fontSizeCaptionSmall: 9,
  midBlue: '#295077',
  lightBlue: '#C5D5EB',
  darkGray: '#4D4E4D',
  midGray: '#767A7C',
  lightGray: '#EDEDED',
  white: '#ffffff',
  black: '#000000',
  red: '#F04C54',
  grayBlue: '#94A0AE',
  familyLight: 'HelveticaNeue',
  familyItalic: 'HelveticaNeue-Italic',
  familyRegular: 'HelveticaNeue-Light',
  familyMedium: 'HelveticaNeue-Medium',
  familyBold: 'HelveticaNeue-Bold',
};
